-- Таблица рейтингов MPA
CREATE TABLE IF NOT EXISTS mpa_ratings (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name VARCHAR(50) NOT NULL UNIQUE
    );

-- Таблица жанров
CREATE TABLE IF NOT EXISTS genres (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name VARCHAR(255) NOT NULL UNIQUE
    );

-- Таблица пользователей
CREATE TABLE IF NOT EXISTS users (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 email VARCHAR(255) NOT NULL UNIQUE,
    login VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    birthday DATE
    );

-- Таблица фильмов
CREATE TABLE IF NOT EXISTS films (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name VARCHAR(255) NOT NULL,
    description VARCHAR(200),
    release_date DATE,
    duration INTEGER,
    mpa_id INTEGER REFERENCES mpa_ratings(id),
    genre_id INTEGER REFERENCES genres(id)
    );

-- Связь фильмов и жанров (многие-ко-многим)
CREATE TABLE IF NOT EXISTS film_genres (
film_id INTEGER REFERENCES films(id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES genres(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
    );

-- Таблица лайков
CREATE TABLE IF NOT EXISTS film_likes (
    film_id INTEGER REFERENCES films(id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
    );

-- Таблица дружбы (односторонняя)
CREATE TABLE IF NOT EXISTS friendships (
 user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    friend_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, friend_id)
    );
INSERT INTO genres (id, name)
SELECT 1, 'Драма' WHERE NOT EXISTS (SELECT 1 FROM genres WHERE id = 1);

INSERT INTO genres (id, name)
SELECT 2, 'Комедия' WHERE NOT EXISTS (SELECT 1 FROM genres WHERE id = 2);

INSERT INTO genres (id, name)
SELECT 3, 'Мультфильм' WHERE NOT EXISTS (SELECT 1 FROM genres WHERE id = 3);

INSERT INTO genres (id, name)
SELECT 4, 'Триллер' WHERE NOT EXISTS (SELECT 1 FROM genres WHERE id = 4);

INSERT INTO genres (id, name)
SELECT 5, 'Документальный' WHERE NOT EXISTS (SELECT 1 FROM genres WHERE id = 5);

INSERT INTO genres (id, name)
SELECT 6, 'Боевик' WHERE NOT EXISTS (SELECT 1 FROM genres WHERE id = 6);

INSERT INTO mpa_ratings (id, name)
SELECT 1, 'G' WHERE NOT EXISTS (SELECT 1 FROM mpa_ratings WHERE id = 1);

INSERT INTO mpa_ratings (id, name)
SELECT 2, 'PG' WHERE NOT EXISTS (SELECT 1 FROM mpa_ratings WHERE id = 2);

INSERT INTO mpa_ratings (id, name)
SELECT 3, 'PG-13' WHERE NOT EXISTS (SELECT 1 FROM mpa_ratings WHERE id = 3);

INSERT INTO mpa_ratings (id, name)
SELECT 4, 'R' WHERE NOT EXISTS (SELECT 1 FROM mpa_ratings WHERE id = 4);

INSERT INTO mpa_ratings (id, name)
SELECT 5, 'NC-17' WHERE NOT EXISTS (SELECT 1 FROM mpa_ratings WHERE id = 5);

